name: ${project.name}
authors: [James Gavin]
version: ${project.version}-${git.commit.id.abbrev}
main: ${project.groupId}.${project.artifactId}
commands:
  freeze:
    description: Freeze another player
    aliases:
      - panic
  mod:
    description: Enable or disable mod mode
    aliases:
      - staff
      - h
  vanish:
    description: Enable or disable vanish
    aliases:
      - v
  reports:
    description: View active and inactive reports
  invsee:
    description: View inside a players inventory